# azure-pipelines.yml
# This pipeline runs your Selenium tests from your GitHub repository

trigger:
- main # Triggers the pipeline on pushes to the main branch

pool:
  vmImage: 'ubuntu-latest' # Use a hosted Ubuntu agent

steps:
- checkout: self # This step checks out your GitHub repository into the agent's workspace
  displayName: 'Checkout code from GitHub'

- task: UsePythonVersion@0 # Azure DevOps task to set up Python
  displayName: 'Set up Python 3.9'
  inputs:
    versionSpec: '3.9' # Specify the Python version

- script: | # Use 'script' for running shell commands
    echo "Installing Python dependencies..."
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script: | # Use 'script' for running shell commands
    echo "Installing Chrome browser..."
    sudo apt-get update
    sudo apt-get install google-chrome-stable -y
    # Verify Chrome installation
    google-chrome --version
  displayName: 'Install Chrome Browser'

- script: | # Use 'script' for running shell commands
    echo "Running Selenium tests with Pytest..."
    python -m pytest tests/test_azure.py
  displayName: 'Run Selenium Tests'