name: Run Selenium Tests

on:
  push:
    branches:
      - main # or master, depending on your default branch
  pull_request:
    branches:
      - main # or master

jobs:
  selenium-test:
    runs-on: ubuntu-latest # You can also use windows-latest or macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or any other Python version you prefer (e.g., 3.10, 3.11)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install Chrome browser for Selenium to use
        sudo apt-get update
        sudo apt-get install google-chrome-stable -y

    - name: Run Selenium tests with Pytest
      run: |
        pytest tests/test_azure.py